### ISSUE TITLE
Type check failed in binding %RESOURCES

### ISSUE THREAD

**Issue by titsuki** [hoelzro/p6-native-resources#1]
I faced the following error in my environment.

```
$ mi6 test
===SORRY!===
Type check failed in binding %RESOURCES; expected Associative but got Nil
```
- My code is
  - https://github.com/okaoka/p6-Algorithm-KdTree/tree/fix-resource
- My environment is

```
$ perl6 -version
This is Rakudo version 2016.01 built on MoarVM version 2016.01
implementing Perl 6.c.

$ uname -a
Linux debian 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux
```

**Comment by hoelzro** [comment]
Hi @okaoka, thanks for reporting the issue!

I don't think this is an issue with `Native::Resources`, but rather one with `mi6`.  `panda-build` works perfectly fine.  I'm guessing that `mi6` isn't doing something to set `%?RESOURCES' properly for`Native::Resources` to pick up.

**Comment by titsuki** [comment]
Thanks for answering !
Then I'll study how App::Mi6 handles `%?RESOURCES` when I have a time.

**Comment by titsuki** [comment]
Sorry for the late reply.
I found that neither `mi6` nor `Native::Resources` itself have any problems.
https://rt.perl.org/Public/Bug/Display.html?id=128101

So, I close this issue.
